name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          docker buildx build \
            --cache-to type=inline \
            --cache-from type=registry,ref=mortware/web:cache \
            --tag mortware/web:latest \
            --tag mortware/web:${{ github.sha }} \
            --push \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name app-mortware \
            --resource-group rg-mortware \
            --image mortware/web:latest

      - name: Verify Deployment
        run: |
          az containerapp show \
            --name app-mortware \
            --resource-group rg-mortware \
            --query "{name:name, status:properties.provisioningState, image:properties.configuration.activeRevisions[0].image}" \
            --output table
